## Load image with software requirements for libnnpdf
image: zaharid/conda-centos

stages:
    - build-deploy

#Set to "true" to upload builds for non-default branches
variables:
  UPLOAD_NON_MASTER: "true"
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
  GIT_DEPTH: 1000
  
## Run the configure and make tests
job1:
    stage: build-deploy
    script:
      - ".ciscripts/build-deploy.sh"
    variables:
        CONDA_PY: "36"
    artifacts:
        untracked: True
