#
# Configuration file for n3fit
#

############################################################
description: NNPDF3.1 NNLO fitted charm global dataset

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
dataset_inputs:
# Fixed target DIS
- {dataset: NMCPD, frac: 0.75 }
- {dataset: NMC,   frac: 0.75  }
- {dataset: SLACP, frac: 0.75}
- {dataset: SLACD, frac: 0.75}
- {dataset: BCDMSP, frac: 0.75}
- {dataset: BCDMSD, frac: 0.75}
- {dataset: CHORUSNUPb, frac: 0.75}
- {dataset: CHORUSNBPb, frac: 0.75}
- {dataset: NTVNUDMNFe, frac: 0.75, cfac: [MAS]}
- {dataset: NTVNBDMNFe, frac: 0.75, cfac: [MAS]}
- {dataset: HERACOMBNCEM, frac: 0.75}
- {dataset: HERACOMBNCEP460, frac: 0.75}
- {dataset: HERACOMBNCEP575, frac: 0.75}
- {dataset: HERACOMBNCEP820, frac: 0.75}
- {dataset: HERACOMBNCEP920, frac: 0.75}
- {dataset: HERACOMBCCEM, frac: 0.75}
- {dataset: HERACOMBCCEP, frac: 0.75}
- {dataset: HERACOMB_SIGMARED_C, frac: 0.75}
- {dataset: HERACOMB_SIGMARED_B, frac: 0.75}
- {dataset: DYE886R, frac: 1.0}
- {dataset: DYE886P, frac: 0.75, cfac: [QCD]}
- {dataset: DYE605, frac: 0.75, cfac: [QCD]}
- {dataset: CDFZRAP, frac: 1.0, cfac: [QCD]}
- {dataset: D0ZRAP, frac: 1.0, cfac: [QCD]}
- {dataset: D0WMASY, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASWZRAP36PB, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASZHIGHMASS49FB, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASLOMASSDY11EXT, frac: 1.0, cfac: [QCD]}

- {dataset: ATLAS_WZ_TOT_13TEV, frac: 1.0, cfac: [NRM, QCD]}

- {dataset: ATLASZPT8TEVMDIST, frac: 0.75, cfac: [QCD], sys: 10}
- {dataset: ATLASZPT8TEVYDIST, frac: 0.75, cfac: [QCD], sys: 10}
- {dataset: ATLASTTBARTOT, frac: 1.0, cfac: [QCD]}
- {dataset: ATLASPHT15, frac: 0.75, cfac: [QCD, EWK]}
- {dataset: CMSWEASY840PB, frac: 1.0, cfac: [QCD]}
- {dataset: CMSWMASY47FB, frac: 1.0, cfac: [QCD]}
- {dataset: CMSDY2D11, frac: 0.75, cfac: [QCD]}
- {dataset: CMSWMU8TEV, frac: 1.0, cfac: [QCD]}
- {dataset: CMSZDIFF12, frac: 1.0, cfac: [QCD, NRM], sys: 10}
- {dataset: CMSTTBARTOT, frac: 1.0, cfac: [QCD]}
- {dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 1.0, cfac: [QCD]}
- {dataset: LHCBZ940PB, frac: 1.0, cfac: [QCD]}
- {dataset: LHCBZEE2FB, frac: 1.0, cfac: [QCD]}
- {dataset: LHCBWZMU7TEV, frac: 1.0, cfac: [NRM, QCD]}
- {dataset: LHCBWZMU8TEV, frac: 1.0, cfac: [NRM, QCD]}





############################################################
datacuts:
  t0pdfset     : NNPDF31_nnlo_as_0118 # PDF set to generate t0 covmat
  q2min        : 3.49                # Q2 minimum
  w2min        : 12.5                # W2 minimum
  combocuts    : NNPDF31             # NNPDF3.0 final kin. cuts
  jetptcut_tev : 0                   # jet pt cut for tevatron
  jetptcut_lhc : 0                   # jet pt cut for lhc
  wptcut_lhc   : 30.0                # Minimum pT for W pT diff distributions
  jetycut_tev  : 1e30                # jet rap. cut for tevatron
  jetycut_lhc  : 1e30                # jet rap. cut for lhc
  dymasscut_min: 0                   # dy inv.mass. min cut
  dymasscut_max: 1e30                # dy inv.mass. max cut
  jetcfactcut  : 1e30                # jet cfact. cut

############################################################
theory:
  theoryid: 53        # database id

############################################################
fitting:

  trvlseed: 1
  nnseed: 2
  mcseed: 3
  load: 'developing_weights.h5'

  genrep   : true    # true = generate MC replicas, false = use real data

  parameters: # This defines the parameter dictionary that is passed to the Model Trainer
    nodes_per_layer: [50, 35, 25, 8]
    activation_per_layer: ['tanh', 'sigmoid', 'sigmoid', 'linear']
    initializer: 'glorot_normal'
    optimizer:
        optimizer_name: 'Adadelta'
        learning_rate: 1.0
    epochs: 2000
    ntegrability:
      initial:
      multiplier: 1.03
    positivity:
        initial:
        multiplier: 1.10
    stopping_patience: 0.1 # percentage of the number of epochs
    layer_type: 'dense'
    dropout: 0.001

  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: NN31IC # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      # pos: True for NN squared
      # mutsize: mutation size
      # mutprob: mutation probability
      # smallx, largex: preprocessing ranges
      - { fl: sng, pos: False, mutsize: [15], mutprob: [0.05], smallx: [1.04,1.20], largex: [1.45,2.64] }
      - { fl: g,   pos: False, mutsize: [15], mutprob: [0.05], smallx: [0.82,1.31], largex: [0.20,6.17] }
      - { fl: v,   pos: False, mutsize: [15], mutprob: [0.05], smallx: [0.51,0.71], largex: [1.24,2.80] }
      - { fl: v3,  pos: False, mutsize: [15], mutprob: [0.05], smallx: [0.23,0.63], largex: [1.02,3.14] }
      - { fl: v8,  pos: False, mutsize: [15], mutprob: [0.05], smallx: [0.53,0.75], largex: [0.70,3.31] }
      - { fl: t3,  pos: False, mutsize: [15], mutprob: [0.05], smallx: [-0.45,1.41], largex: [1.78,3.21] }
      - { fl: t8,  pos: False, mutsize: [15], mutprob: [0.05], smallx: [0.49,1.32], largex: [1.42,3.13] }
      - { fl: cp,  pos: False, mutsize: [15], mutprob: [0.05], smallx: [-0.07,1.13], largex: [1.73,7.37] }

############################################################
positivity:
  posdatasets:
    - { dataset: POSF2U,   poslambda: 1e6 }  # Positivity Lagrange Multiplier
    - { dataset: POSF2DW,  poslambda: 1e6 }
    - { dataset: POSDYU,   poslambda: 1e10 }
    - { dataset: POSDYD,   poslambda: 1e10 }
    - { dataset: POSDYS,   poslambda: 1e10 }
    - {dataset: POSXDB, poslambda: 1e6}
    - {dataset: POSXSQ, poslambda: 1e6}
    - {dataset: POSXSB, poslambda: 1e6}
    - {dataset: POSXGL, poslambda: 1e6}


integrability:
 integdatasets:
    - { dataset: INTEGXT8,   poslambda: 1e2 }
    - { dataset: INTEGXT3,   poslambda: 1e2 }

############################################################
lhagrid:
  nx  : 150
  xmin: 1e-9
  xmed: 0.1
  xmax: 1.0
  nq  : 50
  qmax: 1e5

############################################################
debug: True
maxcores: 4
