#
# Configuration file for NNPDF++
#

############################################################
description: NNPDF4.0 NNLO global

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
dataset_inputs:
# Fixed target DIS
  - {dataset: NMCPD,      frac: 0.5}
  - {dataset: NMC,        frac: 0.5}
  - {dataset: SLACP,      frac: 0.5}
  - {dataset: SLACD,      frac: 0.5}
  - {dataset: BCDMSP,     frac: 0.5}
  - {dataset: BCDMSD,     frac: 0.5}
  - {dataset: CHORUSNUPb, frac: 0.5}
  - {dataset: CHORUSNBPb, frac: 0.5}
  - {dataset: NTVNUDMNFe, frac: 0.5, cfac: [MAS]}
  - {dataset: NTVNBDMNFe, frac: 0.5, cfac: [MAS]}
# Collider DIS (HERA combined)
  - {dataset: HERACOMBNCEM,    frac: 0.5}
  - {dataset: HERACOMBNCEP460, frac: 0.5}
  - {dataset: HERACOMBNCEP575, frac: 0.5}
  - {dataset: HERACOMBNCEP820, frac: 0.5}
  - {dataset: HERACOMBNCEP920, frac: 0.5}
  - {dataset: HERACOMBCCEM,    frac: 0.5}
  - {dataset: HERACOMBCCEP,    frac: 0.5}
# Combined HERA charm production cross-sections
  - {dataset: HERACOMB_SIGMARED_C, frac: 0.5} # N
# Combined HERA bottom production cross-sections
  - {dataset: HERACOMB_SIGMARED_B, frac: 0.5} # N
# Fixed target Drell-Yan
  - {dataset: DYE886R, frac: 1.0}
  - {dataset: DYE886P, frac: 0.5, cfac: [QCD]}
  - {dataset: DYE605,  frac: 0.5, cfac: [QCD]}
# Tevatron W,Z production
  - {dataset: CDFZRAP, frac: 1.0, cfac: [QCD]}
  - {dataset: D0ZRAP,  frac: 1.0, cfac: [QCD]}
  - {dataset: D0WEASY, frac: 1.0, cfac: [QCD]}
  - {dataset: D0WMASY, frac: 1.0, cfac: [QCD]}
# ATLAS DY and EW
  - { dataset: ATLASWZRAP36PB,       frac: 1.0, cfac: [QCD]}
  - { dataset: ATLASZHIGHMASS49FB,   frac: 1.0, cfac: [QCD]}
  - { dataset: ATLASLOMASSDY11EXT,   frac: 1.0, cfac: [QCD]}
  - { dataset: ATLASWZRAP11CC,       frac: 0.5, cfac: [QCD]}      # N
  - { dataset: ATLASWZRAP11CF,       frac: 0.5, cfac: [QCD]}      # N
  - { dataset: ATLASDY2D8TEV,        frac: 0.5, cfac: [QCDEWK]}   # N
  - { dataset: ATLAS_WZ_TOT_13TEV,   frac: 1.0, cfac: [NRM,QCD]}  # N
  - { dataset: ATLAS_WP_JET_8TEV_PT, frac: 0.5, cfac: [QCD]}      # N
  - { dataset: ATLAS_WM_JET_8TEV_PT, frac: 0.5, cfac: [QCD]}      # N
# ATLAS ZpT
  - {dataset: ATLASZPT8TEVMDIST, frac: 0.5, cfac: [QCD], sys: 10}
  - {dataset: ATLASZPT8TEVYDIST, frac: 0.5, cfac: [QCD], sys: 10}
# ATLAS TOP PAIR PRODUCTION
  - {dataset: ATLASTTBARTOT,                       frac: 1.0, cfac: [QCD]}    
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TPTNORM,      frac: 1.0, cfac: [QCD]} # N
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM,     frac: 1.0, cfac: [QCD]} # N
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM,      frac: 1.0, cfac: [QCD]} # N
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM,    frac: 1.0, cfac: [QCD]} # N
  - {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM, frac: 1.0, cfac: [QCD]} # N
# ATLAS SINGLE JETS
  - {dataset: ATLAS_1JET_8TEV_R06_DEC, frac: 0.5, cfac: [QCD]} # N
# ATLAS DIJETS
  - {dataset: ATLAS_2JET_7TEV_R06, frac: 0.5, cfac: [QCD]} # N
# ATLAS DIRECT PHOTON
  - {dataset: ATLASPHT15, frac: 0.5, cfac: [QCD,EWK]} # N
# ATLAS SINGLE TOP
  - {dataset: ATLAS_SINGLETOP_TCH_R_7TEV,                  frac: 1.0, cfac: [QCD]}  # N
  - {dataset: ATLAS_SINGLETOP_TCH_R_13TEV,                 frac: 1.0, cfac: [QCD]}  # N
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM,    frac: 1.0, cfac: [QCD]}  # N
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM, frac: 1.0, cfac: [QCD]}  # N
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM,    frac: 0.5, cfac: [QCD]}  # N
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM, frac: 0.5, cfac: [QCD]}  # N
# CMS DY and EW
  - { dataset: CMSWEASY840PB, frac: 1.0, cfac: [QCD] }
  - { dataset: CMSWMASY47FB,  frac: 1.0, cfac: [QCD] }
  - { dataset: CMSDY2D11,     frac: 0.5, cfac: [QCD] }
  - { dataset: CMSWMU8TEV,    frac: 1.0, cfac: [QCD] }
# CMS Z pt
  - { dataset: CMSZDIFF12,   frac: 1.0, cfac: [QCD,NRM], sys: 10 }
# CMS DIJETS
  - {dataset: CMS_2JET_7TEV,    frac: 0.5, cfac: [QCD]} # N 
  - {dataset: CMS_2JET_3D_8TEV, frac: 0.5, cfac: [QCD]} # N
# CMS TOP PAIR PRODUCTION      
  - {dataset: CMSTTBARTOT,                     frac: 1.0, cfac: [QCD]} 
  - {dataset: CMSTOPDIFF8TEVTTRAPNORM,         frac: 1.0, cfac: [QCD]}
  - {dataset: CMSTTBARTOT5TEV,                 frac: 1.0, cfac: [QCD]} # N
  - {dataset: CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM, frac: 1.0, cfac: [QCD]} # N
  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TRAP, frac: 1.0, cfac: [QCD]} # N
  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TRAP, frac: 1.0, cfac: [QCD]} # N
# CMS SINGLE TOP
  - {dataset: CMS_SINGLETOP_TCH_TOT_7TEV, frac: 1.0, cfac: [QCD]} # N
  - {dataset: CMS_SINGLETOP_TCH_R_8TEV,   frac: 1.0, cfac: [QCD]} # N
  - {dataset: CMS_SINGLETOP_TCH_R_13TEV,  frac: 1.0, cfac: [QCD]} # N
# LHCb EW
  - {dataset: LHCBZ940PB,              frac: 1.0, cfac: [QCD]}
  - {dataset: LHCBZEE2FB,              frac: 1.0, cfac: [QCD]}
  - {dataset: LHCBWZMU7TEV,            frac: 1.0, cfac: [NRM,QCD]}
  - {dataset: LHCBWZMU8TEV,            frac: 1.0, cfac: [NRM,QCD]}
  - {dataset: LHCB_WENU_8TEV_A,        frac: 0.5, cfac: [QCD]} # N
  - {dataset: LHCB_Z_13TEV_DIMUON,     frac: 1.0, cfac: [QCD]} # N
  - {dataset: LHCB_Z_13TEV_DIELECTRON, frac: 1.0, cfac: [QCD]} # N


############################################################
datacuts:
  t0pdfset: 101120-nnpdf40-jcm        # PDF set to generate t0 covmat
  q2min        : 3.49                # Q2 minimum
  w2min        : 12.5                # W2 minimum
  combocuts    : NNPDF31             # NNPDF3.0 final kin. cuts
  jetptcut_tev : 0                   # jet pt cut for tevatron
  jetptcut_lhc : 0                   # jet pt cut for lhc
  wptcut_lhc   : 30.0                # Minimum pT for W pT diff distributions
  jetycut_tev  : 1e30                # jet rap. cut for tevatron
  jetycut_lhc  : 1e30                # jet rap. cut for lhc
  dymasscut_min: 0                   # dy inv.mass. min cut
  dymasscut_max: 1e30                # dy inv.mass. max cut
  jetcfactcut  : 1e30                # jet cfact. cut

############################################################
theory:
  theoryid: 53        # database id

############################################################
fitting:

  trvlseed: 441557204
  nnseed: 4140724068
  mcseed: 1618953082
  save: False
  genrep   : True       # on = generate MC replicas, off = use real data

  parameters: # This defines the parameter dictionary that is passed to the Model Trainer
    nodes_per_layer: [18, 24, 36, 8]
    activation_per_layer: [tanh, sigmoid, sigmoid, linear]
    initializer: glorot_normal
    optimizer:
      clipnorm: 100.0
      learning_rate: 1.0
      optimizer_name: Adadelta
    epochs: 45000
    positivity:
      initial: 338
      multiplier:
    integrability:
      initial: 10
      multiplier:
    stopping_patience: 0.15
    layer_type: dense
    dropout: 0.0
    threshold_chi2: 3.5

  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: EVOL  # EVOL (7), EVOLQED (8), etc.
  basis:
  - {fl: sng, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [1.074, 1.124], largex: [1.471, 3.335]}
  - {fl: g, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [0.8363, 1.083], largex: [2.5, 6.9]}
  - {fl: v, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [0.5741, 0.7375], largex: [1.513, 3.912]}
  - {fl: v3, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [-0.08012, 0.5072], largex: [1.733, 4.053]}
  - {fl: v8, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [0.6088, 0.7906], largex: [1.516, 3.907]}
  - {fl: t3, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [-0.3794, 0.7936], largex: [1.771, 3.825]}
  - {fl: t8, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [0.7167, 1.000], largex: [1.498, 3.772]}
  - {fl: t15, pos: false, trainable: false, mutsize: [15], mutprob: [0.05], smallx: [0.9842, 1.149], largex: [1.464, 3.709]}

############################################################
stopping:
  stopmethod: LOOKBACK  # Stopping method
  lbdelta   : 0         # Delta for look-back stopping
  mingen    : 0         # Minimum number of generations
  window    : 500       # Window for moving average
  minchi2   : 3.5       # Minimum chi2 
  minchi2exp: 6.0       # Minimum chi2 for experiments
  nsmear    : 200       # Smear for stopping
  deltasm   : 200       # Delta smear for stopping
  rv        : 2         # Ratio for validation stopping
  rt        : 0.5       # Ratio for training stopping
  epsilon   : 1e-6      # Gradient epsilon

############################################################
positivity:
  posdatasets:
    - { dataset: POSF2U,   poslambda: 1e6 }  # Positivity Lagrange Multiplier
    - { dataset: POSF2DW,  poslambda: 1e6 }
    - { dataset: POSF2S,   poslambda: 1e6 }
    - { dataset: POSFLL,   poslambda: 1e6 }
    - { dataset: POSDYU,   poslambda: 1e10 }
    - { dataset: POSDYD,   poslambda: 1e10 }
    - { dataset: POSDYS,   poslambda: 1e10 }
    - { dataset: POSF2C,   poslambda: 1e6 }
    - { dataset: POSXUQ,   poslambda: 1e6 }  # Positivity of MSbar PDFs
    - { dataset: POSXUB,   poslambda: 1e6 }
    - { dataset: POSXDQ,   poslambda: 1e6 }
    - { dataset: POSXDB,   poslambda: 1e6 }
    - { dataset: POSXSQ,   poslambda: 1e6 }
    - { dataset: POSXSB,   poslambda: 1e6 }
    - { dataset: POSXGL,   poslambda: 1e6 }
 
############################################################
integrability:
 integdatasets:
    - { dataset: INTEGXT8,   poslambda: 1e2 }
    - { dataset: INTEGXT3,   poslambda: 1e2 }

closuretest:
  filterseed  : 0   # Random seed to be used in filtering data partitions
  fakedata    : False # on = to use FAKEPDF to generate pseudo-data
  fakepdf     : MSTW2008nlo68cl # Theory input for pseudo-data
  errorsize   : 1.0 # uncertainties rescaling
  fakenoise   : False # on = to add random fluctuations to pseudo-data
  rancutprob  : 1.0 # Fraction of data to be included in the fit
  rancutmethod: 0   # Method to select rancutprob data fraction
  rancuttrnval: False # 0(1) to output training(valiation) chi2 in report
  printpdf4gen: False # To print info on PDFs during minimization

############################################################
lhagrid:
  nx  : 150
  xmin: 1e-9
  xmed: 0.1
  xmax: 1.0
  nq  : 50
  qmax: 1e5

############################################################
debug: False
