## Load image with software requirements for libnnpdf
image: zaharid/debian-7-dev

stages:
    - build
    - deploy

## Run the configure and make tests
job1:
    stage: build
    script: ".ciscripts/build-deploy.sh"
    cache:
        untracked: True
    artifacts:
        untracked: True

job2:
    stage: deploy
    script: ls

    #TODO: Do two separate stages when we have a newer version with this
    # implemented (and there are proper docs on how to do it):
    # https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2437
    #
    #
    #No idea why this doesn't work
    #cache:
    #    paths:
    #        - /yes/conda-bld/linux-64/
    #artifacts:
    #    paths:
    #        - /yes/conda-bld/linux-64/

