package:
    name: libnnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build: 
        - python 
        - lhapdf
        - toolchain # [osx] 
        - swig ==3.0.10
        - sqlite
        - gcc <5 # [linux]
        - libgcc # [linux]
        #Gsl doesn't link openblas on old debian 7
        - gsl ==2.2.1 0
        - numpy ==1.13
        - pkg-config
        - cmake
        - libarchive
        - yaml-cpp
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}
    run:
        - lhapdf
        - python 
        - sqlite
        - libgcc # [linux]
        - gsl ==2.2.1 0
        - numpy ==1.13
        - libarchive
        - yaml-cpp
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
