{% set branch = 'nnpdf' + environ.get('CI_BUILD_REF_NAME', 'LOCAL') %}
package:
    name: libnnpdf
    version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: ../

requirements:
    build:
        - python
        - lhapdf
        - swig
        - sqlite
        - gcc <5
        - libgcc <5
        - gsl <2
        - numpy
    run:
        - lhapdf
        - python
        - sqlite
        - libgcc <5
        - gsl    <2
        - numpy
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}
        - {{ branch }}

build:
    number: 0
    detect_binary_files_with_prefix: True
    features:
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}
        - {{ branch }}
    script_env:
        - NNPDF_USE_DOUBLE

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
