package:
    name: libnnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build: 
        - python 
        - lhapdf
        - toolchain # [osx] 
        - pcre
        - sqlite
        - gcc <5 # [linux]
        - libgcc # [linux]
        - gsl
        - numpy
        - pkg-config
        - cmake
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}
    run:
        - lhapdf
        - python 
        - sqlite
        - libgcc # [linux]
        - gsl
        - numpy
        {% if environ.get("NNPDF_USE_DOUBLE", False) %}
        - nnpdf_use_double
        {% endif  %}

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
