package:
    name: libnnpdf
    version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: ../

requirements:
    build: 
        - python 
        - lhapdf
        - swig
        - sqlite
        - gcc
        - libgcc
        - gsl
        - numpy
    run:
        - lhapdf
        - python 
        - sqlite
        - libgcc
        - gsl
        - numpy

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
