package:
    name: libnnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig ==3.0.10
        - cmake
        - pkg-config
    host:
        - python
        - lhapdf
        - sqlite
        #Gsl doesn't link openblas on old debian 7
        - gsl
        - numpy {{ numpy }}
        - libarchive
        - yaml-cpp
    run:
        - lhapdf
        - python
        - sqlite
        - libgcc # [linux]
        - gsl
        - numpy {{ numpy }}
        - libarchive
        - yaml-cpp

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - nnpdf-config

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
