{% set libnnpdf_version = "  1.2.0b5.*" %}
package:
    name: nnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build: 
        - {{ compiler('cxx') }}
        - cmake
        #Found bug in 0.29.2 from the defaults channel
        # https://github.com/ContinuumIO/anaconda-issues/issues/7489#issuecomment-346964337
        - pkg-config ==0.29.1
    host:
        - libnnpdf {{libnnpdf_version}}
        - yaml-cpp
        - apfel >=3
    run:
        - libnnpdf {{libnnpdf_version}}
        - apfel >=3
        - libgcc # [linux]
        - yaml-cpp

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - echo

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
