package:
    name: nnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build: 
        - toolchain # [osx]
        - libnnpdf ==1.1.0b7
        - gcc # [linux]
        - isl # [linux]
        - yaml-cpp
        - cmake
        - apfel
        - pkg-config
    run:
        - libnnpdf
        - apfel
        - libgcc # [linux]
        - yaml-cpp

build:
    number: 0
    detect_binary_files_with_prefix: True

test:
    commands:
        - echo 

about:
    home: https://nnpdf.hepforge.org/
    license: SECRET
