package:
  name: validphys
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - libnnpdf
    - reportengine
    - matplotlib
    - blessings
    - scipy


about:
  home: https://gitlab.cern.ch/NNPDF/validphys2
  license: SECRET
  summary: 'NNPDF analysis framework'

