package:
  name: validphys
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - libnnpdf >=1.1.0b2
    - reportengine >=0.3
    - matplotlib
    - blessings
    - scipy
    - pandas

test:
    imports:
        - validphys

about:
  home: https://gitlab.cern.ch/NNPDF/validphys2
  license: SECRET
  summary: 'NNPDF analysis framework'

