package:
  name: validphys
  version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - libnnpdf >=1.1.0b7
    - reportengine >=0.11
    - matplotlib >=2.0
    - blessings
    - scipy
    - pandas
    - requests

test:
    imports:
        - validphys

about:
  home: https://gitlab.cern.ch/NNPDF/validphys2
  license: SECRET
  summary: 'NNPDF analysis framework'

