# A single CI script with github workflow.
name: Automatic Fit

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build recipe and run tests on linux
      run: |
        conda build -q conda-recipe
    - name: Cleanup conda build
      run: |
        conda build purge-all
    - name: Runner workspace cleanup
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}"