# A single CI script with github workflow.
name: Automatic Fit

on: [push]

env:
  CONDA_PY: 37

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Cleanup workspace
      run: |
        rm -rf ~/miniconda3/conda-bld
        rm -rf ~/miniconda3/envs/*
        rm -rf "${{ github.workspace }}"
    - uses: actions/checkout@v1
    - name: Build recipe
      run: |
        CONDA_PY=$CONDA_PY conda build --no-test -q conda-recipe
    - name: Installing NNPDF conda package
      run: |
        conda create -n nnpdfenv ~/miniconda3/conda-bld/linux-64/*.tar.bz2
    - name: Running fit
      run: |
        export BRANCH=`git branch --show-current`
        export COMMIT=`git rev-parse --short HEAD`
        export RUNCARD=autofit_$BRANCH_$COMMIT.yml
        cd n3fit/runcards
        cp developing.yml $RUNCARD
        conda activate nnpdfenv        
        n3fit $RUNCARD 1
