# A single CI script with github workflow.
name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7]
        include:
          - os: ubuntu-latest
            CONDA_OS: linux-64
          - os: macos-latest
            CONDA_OS: osx-64
    runs-on: ${{ matrix.os }}
    env:
      NETRC_FILE: ${{ secrets.NETRC_FILE }}
      NNPDF_SSH_KEY: ${{ secrets.NNPDF_SSH_KEY }}
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install macOS SDK
      if: startsWith(matrix.os, 'macOS')
      shell: bash -l {0}
      run: |
        conda activate root
        curl -L -O https://data.nnpdf.science/MacOSX10.9.sdk.tar.xz
        tar xfz MacOSX10.9.sdk.tar.xz -C $CONDA_PREFIX
    - name: Setup conda and install conda-build
      shell: bash -l {0}
      run: |
        echo "$NETRC_FILE" | base64 --decode > ~/.netrc
        conda config --append channels conda-forge
        conda config --prepend channels https://packages.nnpdf.science/conda
        conda config --prepend channels https://packages.nnpdf.science/conda-private
        conda config --set show_channel_urls true
        conda activate root
        conda install conda-build --yes
    - name: Build recipe and run tests on linux
      if: startsWith(matrix.os, 'ubuntu')
      shell: bash -l {0}
      run: |
        conda activate root
        conda build -q conda-recipe
    - name: Build recipe and run tests on macOS
      if: startsWith(matrix.os, 'macOS')
      shell: bash -l {0}
      run: |
        conda activate root
        export CONDA_BUILD_SYSROOT=$CONDA_PREFIX/MacOSX10.9.sdk
        conda build -q conda-recipe
    - name: Upload conda package to NNPDF server
      if: github.ref == 'refs/heads/master'
      shell: bash -l {0}
      run: |
        KEY=$( mktemp )
        echo "$NNPDF_SSH_KEY" | base64 --decode > "$KEY"
        conda activate root
        scp -i "$KEY" -o StrictHostKeyChecking=no\
          $CONDA_PREFIX/conda-bld/${{matrix.CONDA_OS}}/*.tar.bz2 \
          dummy@package.nnpdf.science:~/packages/conda-private/linux-64
    - name: Build and upload sphinx documentation to NNPDF server
      if: startsWith(matrix.os, 'ubuntu') && github.ref == 'refs/heads/master'
      shell: bash -l {0}
      run: |
        conda activate root
        conda install nnpdf --yes
        cd doc/sphinx
        make html
        scp -i "$KEY" -o StrictHostKeyChecking=no\
          build/html/* \
          dummy@package.nnpdf.science:~/sphinx-docs/
